autses/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'autses'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name = 'login.html',
    ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name = 'logout.html',
    ), name='logout'),
    path('loggedin/', views.loggedin, name='loggedin'),
]

booksf/urls.py
from django.urls import path

from . import views

app_name = 'booksfinder'

urlpatterns = [
    path('', views.base, name='base'),
]

eventl/urls.py
from django.urls import path

from . import views

app_name = 'accordion'

urlpatterns = [
    path('', views.base, name='base'),
    path('randfact/', views.rand_fact, name='randfact'),
]

news/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('base/', views.base, name='base'),
    path('', include('poster.urls')),
    path('accordion/', include('eventl.urls')),
    path('booksfinder/', include('booksf.urls')),
    path('', include('autses.urls')),
]

poster/urls.py
from django.urls import path

from . import views

app_name = 'index'

urlpatterns = [
    path('', views.index, name='index'),
]

autses/models.py
from django.db import models

# Create your models here.

booksf/models.py
from django.db import models

# Create your models here.

eventl/models.py
from django.db import models

# Create your models here.

poster/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class PostCard(models.Model):
    status_text = models.TextField(max_length=300, default='')
    status_time = models.DateTimeField(auto_now_add=True)

booksf/forms.py
from django import forms

class SearchForm(forms.Form):
    search_query = forms.CharField(label='Search')

poster/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from .models import PostCard

class PostForm(forms.ModelForm):
    class Meta:
        model = PostCard
        exclude = ['status_time']

        labels = {
            'status_text' : ''
        }

        error_messages = {
            'status_text' : {
                'max_length' : _('')
            }
        }

autses/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def loggedin(request):
    return render(request, 'loggedin.html')

booksf/views.py
from django.shortcuts import render, reverse
from django.http import JsonResponse
from . import forms

# Create your views here.

def base(request):
    context = {
        'search_form' : forms.SearchForm(),
    }

    return render(request, 'booksfinder.html', context)

eventl/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from bs4 import BeautifulSoup
import requests, json, random

# Create your views here.

def base(request):
    context = {}

    return render(request, 'accordion.html', context)

def rand_fact(request):
    context = {}

    content = requests.get('http://randomfactgenerator.net/').content.decode()
    content = content[content.find('<html'):]
    content_soup = BeautifulSoup(content, 'html.parser')
    fact = content_soup.findAll('div', {'id' : 'z'})
    fact = fact[random.randint(0, len(fact) - 1)]

    context['content'] = fact.contents[0]

    return render(request, 'base/empty.html', context)

news/views.py
from django.shortcuts import render, reverse

# Create your views here.

def base(request):
    context = {}

    return render(request, 'base.html', context)

poster/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect
from .forms import PostForm
from .models import PostCard

# Create your views here.

def index(request):
    context = {}
    
    context['post_list'] = PostCard.objects.all()

    if request.method == 'GET':
        context['post_form'] = PostForm()
    elif request.method == 'POST':
        post_form = PostForm(request.POST)
        if post_form.is_valid():
            context['post_form'] = PostForm()
            post_form.save()
            return HttpResponseRedirect(reverse('index:index'))
        else:
            context['post_form'] = post_form
            context['error'] = 'Maximum character is 300'

    return render(request, 'index.html', context)

autses/templates/loggedin.html
{% extends 'base.html' %}

{% block includejs %}
<script>
$(function () {
    setTimeout(function () {
        window.location.href = "{% url 'index:index' %}";
    }, 3000);
});
</script>
{% endblock %}
    
{% block content %}
<div style="text-align: center;">
    Hello {{ user.first_name }}
</div>
{% endblock %}
    

autses/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block includecss %}
<link rel="stylesheet" type="text/css" href="{% static 'autses/css/loginstyle.css' %}">
{% endblock %}

{% block content %}

<div class="centerized-div" style="margin-top: 20px;">
    <div>
        <div id="message-container">
            {% if form.errors %}
            <p>Your username and password didn't match. Please try again.</p>
            {% endif %}
        </div>
        
        <div>
            {% if next %}
                {% if user.is_authenticated %}
                <p style="text-align: center;">Your account doesn't have access to this page. To proceed,
                please login with an account that has access.</p>
                {% else %}
                <p style="text-align: center;">Please login to see this page.</p>
                {% endif %}
            {% endif %}
        </div>
        
        <div>
            <form method="post" action="{% url 'autses:login' %}">
            {% csrf_token %}
            <div class="centerized-div">
                <div>
                    <table>
                    <tr>
                        <td>{{ form.username.label_tag }}</td>
                        <td>{{ form.username }}</td>
                    </tr>
                    <tr>
                        <td>{{ form.password.label_tag }}</td>
                        <td>{{ form.password }}</td>
                    </tr>
                    </table>
                
                    <div class="centerized-div">
                        <input type="submit" value="login">
                    </div>
                </div>
            </div>
            <input type="hidden" name="next" value="{% url 'autses:loggedin' %}">
            </form>
        </div>
    </div>
</div>

{% endblock %}

autses/templates/logout.html
{% extends 'base.html' %}

{% block includejs %}
<script>
$(function () {
    setTimeout(function () {
        window.location.href = "{% url 'index:index' %}";
    }, 3000);
});
</script>
{% endblock %}

{% block content %}
<div class="centerized-div" style="text-align: center;">
    You've been logged out <br> You'll be redirected in a few seconds
</div>
{% endblock %}
    

booksf/templates/booksfinder.html
{% extends 'base.html' %}
{% load static %}

{% block includecss %}
<link rel="stylesheet" type="text/css" href="{% static 'booksf/css/booksfinder.css' %}">
{% endblock %}

{% block includejs %}
<script src="{% static 'booksf/js/booksfinder.js' %}"></script>
{% endblock %}

{% block title %}Where You Find Book{% endblock %}

{% block content %}
<div id="title-bar">
    The Title
</div>
<div class="row">
    <div class="col-0  col-lg-2"></div>
    <div class="col-12 col-lg-8">
        <div id="search-field">
        {% for field in search_form %}
            <label for="{{ field.auto_id }}" class="input-label">{{ field.label }} : </label>{{ field }}
        {% endfor %}
        </div>
        <button id="search-button">
            Search
        </button>
    </div>
    <div class="col-0  col-lg-2"></div>

    <div class="col-1 "></div>
    <div class="col-10">
        <div>
            <pageidx>0</pageidx>/<pagecount>0</pagecount>
        </div>
        <div id="nav-button">
            <div>
                <button id="prev-button">
                    Prev
                </button>
            </div>
            <div>
                <select id="result-count">
                    <option value="10">10</option>
                    <option value="20">20</option>
                    <option value="30">30</option>
                    <option value="40">40</option>
                </select>
            </div>
            <div>
                <button id="next-button">
                    Next
                </button>
            </div>
        </div>
        <div id="search-result">
            <table id="result-table">
                <tr>
                    <th class="tc-1"><div class="table-text">Title</div></th>
                    <th class="tc-2"><div class="table-text">Description</div></th>
                    <th class="tc-3"><div class="table-text">Cover</div></th>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-1 "></div>
</div>
{% endblock %}

eventl/templates/accordion.html
{% extends 'base.html' %}
{% load static %}

{% block includecss %}
<link rel="stylesheet" type="text/css" href="{% static 'eventl/css/accordion.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'eventl/css/colorpicker.css' %}">
{% endblock %}

{% block includejs %}
<script src="{% static 'eventl/js/accordion.js' %}"></script>
<script src="{% static 'eventl/js/getcolor.js' %}"></script>
{% endblock %}
    
{% block title %}
    Interesting Title
{% endblock %}


{% block content %}
<div class="row white">
    <div class="col-md-3 left-column"></div>
    <div class="col-10 col-md-6 main-col">
        <div class="card header-bar black">
            <h1>
                Extended Profile
            </h1>
        </div>

        <div class="accordion-container">
            <div class="accordion-card black">
                <h2 class="accordion-title">
                    Aktivitas
                </h2>
                <div class="accordion-content">
                    <p>
                        - Kuliah<br>
                        - Sinematografi
                    </p>
                </div>
            </div>
            <div class="accordion-card black">
                <h2 class="accordion-title">
                    Pengalaman Organisasi/Kepanitiaan
                </h2>
                <div class="accordion-content">
                    <p>
                        - Multimedia Sonic Linguistic 2017<br>
                        - Multimedia Sonic Linguistic 2018<br>
                        - Documentation and Animation Compfest 11<br>
                        - Animation and Video UIFF 2019
                    </p>
                </div>
            </div>
            <div class="accordion-card black">
                <h2 class="accordion-title">
                    Prestasi
                </h2>
                <div class="accordion-content">
                    <p>
                        TBA
                    </p>
                </div>
            </div>
        </div>

        <div id="fact-container">
            <p id="fact-text" class="black">

            </p>
            <br>
            <p id="fact-credit" class="black">
                generated using <a href="http://randomfactgenerator.net/" target="_blank">randomfactgenerator.net</a>
            </p>
            <br>
            <p id="color-button" class="black">
                Change<br>
                Background Color
            </p>
        </div>
        <div id="picker-container">
            <div id="color-picker">
                <div id="box1">
                    <div id="box2">
                        <div id="box3">

                        </div>
                        <div id="box4">
                            <div id="box5">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-2 col-md-3">
        <div class="switch-button">
            <div class="switch-indicator">

            </div>
        </div>
        <h2 style="text-align: right;">Switch Theme</h2>
    </div>
</div>
{% endblock %}

eventl/templates/base/bootstrap.html
<!-- bootstrap loader template -->
{% load static %}
<link rel="stylesheet" type="text/css" href={% static 'css/bootstrap/bootstrap.css' %}>
<link rel="stylesheet" type="text/css" href={% static 'css/bootstrap/bootstrap-grid.css' %}>
<link rel="stylesheet" type="text/css" href={% static 'css/bootstrap/bootstrap-reboot.css' %}>

eventl/templates/base/empty.html
{{ content }}

poster/templates/boot_template.html
<!-- bootstrap loader template -->
{% load static %}
<link rel="stylesheet" type="text/css" href={% static 'css/bootstrap/bootstrap.css' %}>
<link rel="stylesheet" type="text/css" href={% static 'css/bootstrap/bootstrap-grid.css' %}>
<link rel="stylesheet" type="text/css" href={% static 'css/bootstrap/bootstrap-reboot.css' %}>

poster/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
The Story
{% endblock %}
    

{% block includecss %}
<link rel="stylesheet" type="text/css" href={% static 'css/index.css' %}>
{% endblock %}

{% block content %}
    <div style="text-align: center; margin-top: 50px;">
        <h1>
            Halo, apa kabar?
        </h1>
    </div>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-10">
            <div>
                <form method="post">
                    {% csrf_token %}

                    {{ post_form.as_p }}
                    <input id="id_submit_button" type="submit" value="Post">
                </form>
                
                {% if error %}
                    <error>
                        <div>
                            {{ error }}
                        </div>
                    </error>
                {% endif %}
                    
            </div>
            <div id="columns">                
                {% for post in post_list %}
                <postcard>
                    <div class="postcard">
                        <p>
                            {{ post.status_text }}
                        </p>
                        <p>
                            {{ post.status_time }}
                        </p>
                    </div>
                </postcard>
                {% endfor %}
                    
            </div>
        </div>
        <div class="col-1"></div>
    </div>
{% endblock %}

templates/base.html
<!-- Base Html, Include bootstrap and jquery -->
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap/bootstrap-grid.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap/bootstrap-reboot.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {% block includecss %}{% endblock %}
    <script src="{% static 'js/jquery/jquery-3.4.1.js' %}"></script>
    {% block includejs %}{% endblock %}
    <title>{% block title %}Base Title{% endblock title %}</title>
    <style></style>
</head>
<body>
    <div id="nav-bar">
        <div class="row">
            <div class="col-lg-4" id="navigation-button">
                <div>
                    <a href="{% url 'index:index' %}">
                        <button>
                            Home
                        </button>
                    </a>
                    <a href="{% url 'accordion:base' %}">
                        <button>
                            Accordion
                        </button>
                    </a>
                    <a href="{% url 'booksfinder:base' %}">
                        <button>
                            Books Finder
                        </button>
                    </a>
                </div>
            </div>
            <div class="col-lg-4" id="center-content">
                Center Content
            </div>
            <div class="col-lg-4" id="user-button">
                <div>
                    {% if user.is_authenticated %}
                    <a href="{% url 'autses:logout' %}">
                        <button>
                            Logout
                        </button>
                    </a>
                    {% else %}
                    <a href="{% url 'autses:login' %}">
                        <button>
                            Login
                        </button>
                    </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div id="content">
    {% block content %}
        
    {% endblock content %}
    </div>
</body>
</html>